default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: ww2bam

test:
  <<: *default
  database: ww2bam_test

production:
  <<: *default
  database: ww2bam_prod
